version: "3.5"
services:
 redis:
    image: "redis:6"
    command: ["redis-server",  "--appendonly", "yes"]
    ports:
     - "6379"

 web:
    build:
         dockerfile: Dockerfile
         context: .
    ports:
        - "8000:8000"
    environment:
         - REDIS_URL=tcp://redis:6379
    depends_on:
       - redis
